# Site Settings
title: Objective Art
email: maverickjin88@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/"
url: "http://taniarascia.github.io"
twitter_username: taniarascia
github_username:  taniarascia
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
